### ISSUE TITLE
启动服务器的时候dbmgr报错！！

### ISSUE THREAD

**Issue by macrobin** [kbengine/kbengine_unity3d_plugins#12]
错误日志：Components:: findComponents:find dbmgr

**Comment by kbengine** [comment]
自己看dbmgr的日志吧， 你搭建有问题

**Comment by kbengine** [comment]
论坛搜你的错误也能有一些帮助。

老老问题了

**Comment by scanor** [comment]
这个错误一般是因为你没有创建数据库或者没开数据库。
请看这里：http://kbengine.org/cn/docs/installation.html 
的这一部分：《3. 安装数据库》
按照教程走一遍就能解决问题了
