### ISSUE TITLE
demo登录功能提示找不到onConnectionState

### ISSUE THREAD

**Issue by reatank** [kbengine/kbengine_unity3d_plugins#18]
服务器与unity插件都是1.1.3release版，报错信息如下
[2018-02-01 19:44:27 001] Event::fireIn: event(onConnectionState) not found!
UnityEngine.Debug:LogWarning(Object)
KBEngine.Dbg:WARNING_MSG(Object) (at Assets/Plugins/kbengine_unity3d_plugins/Dbg.cs:47)
KBEngine.Event:fire_(Dictionary`2, LinkedList`1, String, Object[]) (at Assets/Plugins/kbengine_unity3d_plugins/Event.cs:276)
KBEngine.Event:fireAll(String, Object[]) (at Assets/Plugins/kbengine_unity3d_plugins/Event.cs:264)
KBEngine.NetworkInterface:_onConnectionState(ConnectState) (at Assets/Plugins/kbengine_unity3d_plugins/NetworkInterface.cs:116)
System.Reflection.MethodBase:Invoke(Object, Object[])
KBEngine.Event:processInEvents() (at Assets/Plugins/kbengine_unity3d_plugins/Event.cs:365)
KBEngine.KBEngineApp:process() (at Assets/Plugins/kbengine_unity3d_plugins/KBEngine.cs:288)
KBEMain:KBEUpdate() (at Assets/Plugins/kbengine_unity3d_plugins/KBEMain.cs:101)
KBEMain:FixedUpdate() (at Assets/Plugins/kbengine_unity3d_plugins/KBEMain.cs:94)

**Comment by kebiao** [comment]
这个警告不用管
