### ISSUE TITLE
建议插件底层的方法都带上virtual

### ISSUE THREAD

**Issue by guihouchang** [kbengine/kbengine_unity3d_plugins#9]
如果底层都是虚方法的话，方便开发者重载修改，又不影响版本更新，我现在发现我改了底层插件的代码，但是又要更新新版本的插件的时候就很麻烦了，要 一个个文件去比对。

**Comment by liudaafang** [comment]
都加virtual未免有点。。。

插件底层一般不需要改动的，   你可以fork一份， git合并很方便的，不会影响你修改啊。
